config/routes.rb
Rails.application.routes.draw do
  resources :changes

  root 'changes#index'

end

app/models/change.rb
class Change < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  before_action :set_change, only: [:show, :edit, :update, :destroy]

  # GET /changes
  # GET /changes.json
  def index
    @changes = Change.all
  end

  # GET /changes/1
  # GET /changes/1.json
  def show
  end

  # GET /changes/new
  def new
    @change = Change.new
  end

  # GET /changes/1/edit
  def edit
  end

  # POST /changes
  # POST /changes.json
  def create
    @change = Change.new(change_params)

    respond_to do |format|
      if @change.save
        format.html { redirect_to @change, notice: 'Change was successfully created.' }
        format.json { render :show, status: :created, location: @change }
      else
        format.html { render :new }
        format.json { render json: @change.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /changes/1
  # PATCH/PUT /changes/1.json
  def update
    respond_to do |format|
      if @change.update(change_params)
        format.html { redirect_to @change, notice: 'Change was successfully updated.' }
        format.json { render :show, status: :ok, location: @change }
      else
        format.html { render :edit }
        format.json { render json: @change.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /changes/1
  # DELETE /changes/1.json
  def destroy
    @change.destroy
    respond_to do |format|
      format.html { redirect_to changes_url, notice: 'Change was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_change
      @change = Change.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def change_params
      params.require(:change).permit(:title, :description, :version, :size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/views/changes/_form.html.erb
<%= form_for(@change) do |f| %>
  <% if @change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@change.errors.count, "error") %> prohibited this change from being saved:</h2>

      <ul>
      <% @change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_area :version %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_area :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/changes/edit.html.erb
<h1>Editing Change</h1>

<%= render 'form' %>

<%= link_to 'Show', @change %> |
<%= link_to 'Back', changes_path %>

app/views/changes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Changes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Version</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @changes.each do |change| %>
      <tr>
        <td><%= change.title %></td>
        <td><%= change.description %></td>
        <td><%= change.version %></td>
        <td><%= change.size %></td>
        <td><%= link_to 'Show', change %></td>
        <td><%= link_to 'Edit', edit_change_path(change) %></td>
        <td><%= link_to 'Destroy', change, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Change', new_change_path %>

app/views/changes/new.html.erb
<h1>New Change</h1>

<%= render 'form' %>

<%= link_to 'Back', changes_path %>

app/views/changes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @change.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @change.description %>
</p>

<p>
  <strong>Version:</strong>
  <%= @change.version %>
</p>

<p>
  <strong>Size:</strong>
  <%= @change.size %>
</p>

<%= link_to 'Edit', edit_change_path(@change) %> |
<%= link_to 'Back', changes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ViewChanges</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>